{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (
    SELECT * FROM {{ source('raw', 'extracted_articles') }}
),

cleaned AS (
    SELECT
        MD5(CONCAT(COALESCE(TITLE, ''), '|', COALESCE(URL, ''))) AS ARTICLE_ID,
        UPPER(TRIM(SOURCE_NAME)) AS SOURCE_NAME,
        'RSS' AS SOURCE_TYPE,
        TRIM(REGEXP_REPLACE(TITLE, '<[^>]+>', '')) AS TITLE,
        TRIM(REGEXP_REPLACE(DESCRIPTION, '<[^>]+>', '')) AS CONTENT,
        TRIM(URL) AS URL,
        TRIM(AUTHOR) AS AUTHOR,
        TRY_TO_TIMESTAMP(PUBLISHED_DATE) AS PUBLISHED_TIMESTAMP,
        TO_DATE(TRY_TO_TIMESTAMP(PUBLISHED_DATE)) AS PUBLISHED_DATE,
        TRY_TO_TIMESTAMP(COLLECTED_AT) AS COLLECTED_TIMESTAMP,
        LENGTH(DESCRIPTION) AS CONTENT_LENGTH,
        CURRENT_TIMESTAMP() AS DBT_LOADED_AT
    FROM source
    WHERE TITLE IS NOT NULL 
      AND URL IS NOT NULL
),

deduped AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY URL 
            ORDER BY COLLECTED_TIMESTAMP DESC
        ) AS ROW_NUM
    FROM cleaned
)

SELECT * EXCLUDE ROW_NUM
FROM deduped
WHERE ROW_NUM = 1