{{ config(
    materialized='table',
    schema='prod'
) }}

SELECT
    DATE_KEY,
    TOPIC_KEY,
    SOURCE_KEY,
    
    COUNT(*) AS ARTICLE_COUNT,
    AVG(SENTIMENT_SCORE) AS AVG_SENTIMENT_SCORE,
    
    SUM(CASE WHEN SENTIMENT_SCORE > 0.05 THEN 1 ELSE 0 END) AS POSITIVE_COUNT,
    SUM(CASE WHEN SENTIMENT_SCORE < -0.05 THEN 1 ELSE 0 END) AS NEGATIVE_COUNT,
    SUM(CASE WHEN SENTIMENT_SCORE BETWEEN -0.05 AND 0.05 THEN 1 ELSE 0 END) AS NEUTRAL_COUNT,
    
    STDDEV(SENTIMENT_SCORE) AS SENTIMENT_VOLATILITY,
    
    CURRENT_TIMESTAMP() AS CREATED_TIMESTAMP
    
FROM {{ ref('fact_articles') }}
GROUP BY DATE_KEY, TOPIC_KEY, SOURCE_KEY