version: 2

models:
  - name: fact_articles
    description: "Main fact table with all articles"
    columns:
      - name: ARTICLE_ID
        tests:
          - unique
          - not_null
      - name: SENTIMENT_SCORE
        tests:
          - not_null

  - name: dim_date
    columns:
      - name: DATE_KEY
        tests:
          - unique
          - not_null